{#- Grão: um pedido. Já traz estado, status e métricas para consumo direto. -#}
select
    order_id,
    customer_id,
    purchased_at::date                         as purchase_date,
    date_trunc('month', purchased_at)::date    as purchase_month,
    customer_state,
    order_status,
    is_delivered,
    is_cancelled,
    is_unavailable,
    is_revenue_order,
    has_delivery_date,
    is_delayed,
    delay_bucket,
    distance_bucket,
    items_count,
    sellers_count,
    products_value,
    freight_value,
    total_value,
    payments_total,
    main_payment_type,
    max_installments,
    review_score,
    avg_distance_km,
    purchased_at,
    approved_at,
    shipped_at,
    delivered_at,
    estimated_delivery_at,
    days_purchase_to_approval,
    days_approval_to_carrier,
    days_purchase_to_carrier,
    days_carrier_to_customer,
    days_purchase_to_delivery,
    days_late
from {{ ref('int_orders_enriched') }}
